level_0 = {
    'terrain': '../levels/0/level_0_Terrain.csv',
    'coins': '../levels/0/level_0_Coins.csv',
    'fg palms': '../levels/0/level_0_Fg_Palms.csv',
    'bg palms': '../levels/0/level_0_Bg_Palms.csv',
    'crates': '../levels/0/level_0_Crates.csv',
    'enemies': '../levels/0/level_0_Enemies.csv',
    'constraints': '../levels/0/level_0_Constraints.csv',
    'player': '../levels/0/level_0_Player.csv',
    'grass': '../levels/0/level_0_Grass.csv',
    'diamond': '../levels/0/level_0_Diamond.csv',
    'node_pos': (110, 300),
    'unlock': 1,
    'graphics': '../graphics/overworld/0'}
level_1 = {
    'terrain': '../levels/1/level_1_Terrain.csv',
    'coins': '../levels/1/level_1_Coins.csv',
    'fg palms': '../levels/1/level_1_Fg_Palms.csv',
    'bg palms': '../levels/1/level_1_Bg_Palms.csv',
    'crates': '../levels/1/level_1_Crates.csv',
    'enemies': '../levels/1/level_1_Enemies.csv',
    'constraints': '../levels/1/level_1_Constraints.csv',
    'player': '../levels/1/level_1_Player.csv',
    'grass': '../levels/1/level_1_Grass.csv',
    'diamond': '../levels/1/level_1_Diamond.csv',
    'node_pos': (300, 120),
    'unlock': 2,
    'graphics': '../graphics/overworld/1'}
level_2 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (480, 510),
    'unlock': 3,
    'graphics': '../graphics/overworld/2'}
level_3 = {
    'terrain': '../levels/3/level_3_terrain.csv',
    'coins': '../levels/3/level_3_coins.csv',
    'fg palms': '../levels/3/level_3_fg_Palms.csv',
    'bg palms': '../levels/3/level_3_bg_Palms.csv',
    'crates': '../levels/3/level_3_crates.csv',
    'enemies': '../levels/3/level_3_enemies.csv',
    'constraints': '../levels/3/level_3_constraints.csv',
    'player': '../levels/3/level_3_player.csv',
    'grass': '../levels/3/level_3_grass.csv',
    'diamond': '../levels/3/level_3_diamond.csv',
    'node_pos': (610, 300),
    'unlock': 4,
    'graphics': '../graphics/overworld/3'}
level_4 = {
    'terrain': '../levels/4/level_4_terrain.csv',
    'coins': '../levels/4/level_4_coins.csv',
    'fg palms': '../levels/4/level_4_fg_palms.csv',
    'bg palms': '../levels/4/level_4_bg_palms.csv',
    'crates': '../levels/4/level_4_crates.csv',
    'enemies': '../levels/4/level_4_enemies.csv',
    'constraints': '../levels/4/level_4_constraints.csv',
    'player': '../levels/4/level_4_player.csv',
    'grass': '../levels/4/level_4_grass.csv',
    'diamond': '../levels/4/level_4_diamond.csv',
    'node_pos': (880, 110),
    'unlock': 5,
    'graphics': '../graphics/overworld/4'}
level_5 = {
    'terrain': '../levels/5/level_5_terrain.csv',
    'coins': '../levels/5/level_5_coins.csv',
    'fg palms': '../levels/5/level_5_fg_Palms.csv',
    'bg palms': '../levels/5/level_5_bg_Palms.csv',
    'crates': '../levels/5/level_5_crates.csv',
    'enemies': '../levels/5/level_5_enemies.csv',
    'constraints': '../levels/5/level_5_constraints.csv',
    'player': '../levels/5/level_5_player.csv',
    'grass': '../levels/5/level_5_grass.csv',
    'diamond': '../levels/5/level_5_diamond.csv',
    'node_pos': (1050, 300),
    'unlock': 6,
    'graphics': '../graphics/overworld/5'}
level_6 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (1200, 150),
    'unlock': 6,
    'graphics': '../graphics/overworld/0'}
level_7 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (1550, 100),
    'unlock': 7,
    'graphics': '../graphics/overworld/1'}
level_8 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (1750, 350),
    'unlock': 8,
    'graphics': '../graphics/overworld/2'}
level_9 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (1430, 450),
    'unlock': 9,
    'graphics': '../graphics/overworld/3'}
level_10 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (1800, 650),
    'unlock': 10,
    'graphics': '../graphics/overworld/4'}
level_11 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (1530, 875),
    'unlock': 11,
    'graphics': '../graphics/overworld/5'}
level_12 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (1200, 650),
    'unlock': 12,
    'graphics': '../graphics/overworld/0'}
level_13 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (875, 850),
    'unlock': 13,
    'graphics': '../graphics/overworld/1'}
level_14 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (750, 550),
    'unlock': 14,
    'graphics': '../graphics/overworld/2'}
level_15 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (550, 850),
    'unlock': 15,
    'graphics': '../graphics/overworld/3'}
level_16 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (310, 675),
    'unlock': 15,
    'graphics': '../graphics/overworld/4'}
level_17 = {
    'terrain': '../levels/2/level_2_terrain.csv',
    'coins': '../levels/2/level_2_coins.csv',
    'fg palms': '../levels/2/level_2_fg_Palms.csv',
    'bg palms': '../levels/2/level_2_bg_Palms.csv',
    'crates': '../levels/2/level_2_crates.csv',
    'enemies': '../levels/2/level_2_enemies.csv',
    'constraints': '../levels/2/level_2_constraints.csv',
    'player': '../levels/2/level_2_player.csv',
    'grass': '../levels/2/level_2_grass.csv',
    'diamond': '../levels/2/level_2_diamond.csv',
    'node_pos': (110, 550),
    'unlock': 15,
    'graphics': '../graphics/overworld/5'}

levels = {
    0: level_0,
    1: level_1,
    2: level_2,
    3: level_3,
    4: level_4,
    5: level_5,
    6: level_6,
    7: level_7,
    8: level_8,
    9: level_9,
    10: level_10,
    11: level_11,
    12: level_12,
    13: level_13,
    14: level_14,
    15: level_15,
    16: level_16,
    17: level_17,
}
